### ISSUE TITLE
Use Tesseract 4

### ISSUE THREAD

**Issue by rhiaro** [alephdata/ingestors#10]
With an option to switch back to 3.04 in case of emergencies.

**Comment by pudo** [comment]
@rhiaro I'm trying to compile tesserocr against tesseract 4 in a docker container right now. Do you recall how you did that?

**Comment by rhiaro** [comment]
I don't remember specifics, but I think tesseract in this aleph branch was working when I left it: https://github.com/alephdata/aleph/commit/4668ca8d28edb506c60acbee1f6bf1138b0dbeed

**Comment by pudo** [comment]
Oh, I didn't realise it actually shipped with bionic. In that case it's been auto-solved. Thanks!
